### PR TITLE
cms tree

### PR DESCRIPTION
**Pull request by miknaz**

### CODE REVIEW

**Comment by aimeos** [comment]
Thanks. Can you please fix the line indentions? We use one tab per level, no spaces and not more.
Can you also adapt the tests for the item and manager?

**Comment by miknaz** [comment]
@aimeos , sure, np, I will do

**Comment by miknaz** [comment]
@aimeos tell me please, how to run tests ?

**Comment by aimeos** [comment]
- checkout aimeos/aimeos-core
- checkout aimeos/ai-cms-grapesjs in ./aimeos-core/ext/
- execute `composer update` in ./aimeos-core/
- copy ./aimeos-core/config/resource-dist.php to ./aimeos-core/config/resource.php and adapt the DB settings
- run `vendor/bin/phing setup` in ./aimeos-core
- test with `vendor/bin/phing -Ddir=ext/ai-cms-grapesjs testext`

**Pull request closed without merging**
