### PR TITLE
Fixed editor columns insert mode

### PR DESCRIPTION
**Pull request by Dahercode**
https://github.com/aimeos/ai-cms-grapesjs/issues/7

### CODE REVIEW

**Comment by aimeos** [comment]
In our setup this has no effect because it's overwritten by:
```
.gjs-dashed .row, .gjs-dashed .col, .gjs-dashed [class^="col-"] {
	min-height: 1.5rem !important;
}
```

**Comment by Dahercode** [comment]
I think it does, i have the same setup as yours : 

".gjs-dashed .row" is not triggered somehow. You can try ^^

**Comment by aimeos** [comment]
In our case it is and this seems to make the difference. Does it work for you if you use this:
```
		styles: `
			img {
				max-width: 100%;
			}
			form {
				padding: 10px 0;
			}
			.row, .col, [class^="col-"] {
				min-height: 1.5rem !important;
			}
			.row {
				display: flex; padding: 10px 0; width: auto;
			}
			.table {
				border-collapse: initial;
			}
			.table .row {
				display: table-row;
			}
			.table .cell {
				width: auto; height: auto;
			}
			::-webkit-scrollbar {
				background-color: var(--bs-bg, #f8fafc); width: 0.25rem;
			}
			::-webkit-scrollbar-thumb {
				background-color: #505860; outline: none;
			}
			body {
				background-color: #F8FAFC; scrollbar-color: #505860 transparent; scrollbar-width: thin;
			}
			.contact-form .contact-pot {
				display: none;
			}
		`,
```

**Comment by Dahercode** [comment]
Yes, it works just fine

**Comment by aimeos** [comment]
Great! Can you modify your PR accordingly?

**Comment by aimeos** [comment]
Thanks a lot!

**Pull request merged**
